---
- name: Install Other Python dependencies
  apt:
    name: ["python3-dev", "libpq-dev"]
    state: "present"

- name: Install Python
  apt:
    name: ["python", "python3"]
    state: "present"

- name: Install Postgres
  apt:
    name: ["postgresql", "postgresql-contrib",]
    state: "present"

- name: Install Pip
  apt:
    name: "python3-pip"
    state: "present"

- name: Install Nginx
  apt:
    name: "nginx"
    state: "present"

- name: Test to see if pip is installed
  command: pip3 --version
  register: "sestatus"
  changed_when: false
